spring.application.name=telegram-agent-ui-phase3

telegram.bot.name=webt2bot
telegram.bot.token=8768289555:AAGyvcqbPqMkh73dPr63USm3WKnKpJ5kC24

agent.ai.enabled=${AGENT_AI_ENABLED:false}
agent.ai.base-url=${AGENT_AI_BASE_URL:https://api.openai.com/v1}
agent.ai.api-key=${AGENT_AI_API_KEY:}
agent.ai.model=${AGENT_AI_MODEL:gpt-4o-mini}

logging.level.root=INFO
logging.level.com.oraclebot=DEBUG
